services:
  backend:
    volumes:
      - ./backend:/app/backend
    env_file:
      - ./backend/.env.dev.docker
    command: /app/backend/entrypoint.sh

  celery_worker:
    volumes:
      - ./backend:/app/backend
    env_file:
      - ./backend/.env.dev.docker
    command: >
      sh -c "python -m celery -A app.celery_app:celery_app worker
      --loglevel=info --concurrency=2 -Q celery --pool=solo"

  frontend:
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    env_file:
      - ./frontend/.env.docker
      - ./frontend/.env.dev.docker
    command: >
      sh -c "npm install &&
      npm run dev -- --host 0.0.0.0 --port 5173"
